# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Source is previously built image
FROM mini-pupper-base:1.0

RUN sudo apt-get install -y python-pip apt-utils
RUN pip install Inject==3.5.4

ADD robot_ws/src /home/robomaker/workspace/robot_ws/src
ADD simulation_ws/src /home/robomaker/workspace/simulation_ws/src
RUN sudo rosdep fix-permissions && rosdep update

WORKDIR /home/robomaker/workspace/robot_ws


# Build the Robot application
RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && rosdep install --rosdistro melodic --from-paths src --ignore-src -r -y && colcon build && sudo apt clean"

# Add entrypoint script and grant permission
COPY scripts/robot-entrypoint.sh robot-entrypoint.sh
RUN sh -c 'sudo chmod +x robot-entrypoint.sh && sudo chown robomaker:robomaker robot-entrypoint.sh'

RUN sudo mkdir -p /config/certs/

CMD roslaunch mini_pupper_dance dance.launch hardware_connected:=false
ENTRYPOINT [ "/home/robomaker/workspace/robot_ws/robot-entrypoint.sh" ]
